version: '3.8'
services:
  mongodb:
    image: mongo:7-jammy
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
  grafana:
    image: grafana/grafana-oss:latest
    # image:  ghcr.io/ajeje93/grafana-mongodb-docker:latest
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      # - grafana-storage:/var/lib/grafana
      - $PWD/grafana-storage:/var/lib/grafana
    environment:
      - "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=meln5674-mongodb-community"
      - "GF_INSTALL_PLUGINS=https://github.com/meln5674/grafana-mongodb-community-plugin/releases/download/v0.2.0%2Brc4/meln5674-mongodb-community.zip;meln5674-mongodb-community"
volumes:
  mongodata:
  grafana-storage:
